name: manual_build

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'What is the reason to trigger this manually?'
        # Default value if no value is explicitly provided
        default: 'testing github actions'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  manual_build:
    name:  manual_build
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.9'

      - name: python basics
        # should prob shift to requirements.txt, but setting like this for now
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install meltano==2.10.0
      - name: meltano install
        # explicitly not running all installs, since testing the visuals is out of scope
        run: |
          meltano --log-level=debug install extractors
          meltano --log-level=debug install loaders
        
      - name: build it
        run: make foobar
        env:
          TAP_OURA_ACCESS_TOKEN: ${{ secrets.TAP_OURA_ACCESS_TOKEN }}
          TAP_OURA_START_DATE: $${{ secrets.TAP_OURA_START_DATE }}
          
      - name: build evidence
        run: make evidence-build
        
      - name: copy output to working directory
        run: |
          mkdir -p /home/runner/work/_temp/_github_home/build
          cp -r analyze/build/* /home/runner/work/_temp/_github_home/build
        
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true
